services:
  ANTECEDENT:
    container_name: antecedent
    env_file:
    - ./vars/.antecedent.env
    environment:
      Antecedent.app.Email.From: yashar.ghaemi@antecedent.us
      Antecedent.app.jwtSecret: 79Vca64ZShmOsibba649kMrwvjqQYGj0WT2h13NK6B3p6iHLUr1JbzqzT0hm8Y7YUAiAq8M8ApkzqzyLM4gPXXXHaq1UwfE0
      Antecedent.app.ui: https://local.antecedentwriting.com/
      Antecedent.app.url: https://local.antecedentwriting.com/
      
      spring.mail.host: smtp.gmail.com
      spring.mail.password: asd
      spring.mail.port: 587
      spring.mail.username: yashar.ghaemi@antecedent.us
    image: quay.io/antecedent.writing.analytics/antecedent:LT-latest
    ports:
    - 8080:8080
    restart: always
  AWAUI:
    container_name: awaui
    env_file:
    - ./vars/.awaui.env
    environment:
      REACT_APP_ADMIN_EDITOR_URL: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?WOPISrc=https://local.antecedentwriting.com/admin/wopi/files/
      REACT_APP_API_URL: https://local.antecedentwriting.com
      REACT_APP_COLLABORA_HOST: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?
      REACT_APP_EDITOR_URL: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?WOPISrc=https://local.antecedentwriting.com/wopi/files/
      REACT_APP_EDU_EDITOR_URL: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?WOPISrc=https://local.antecedentwriting.com/shadow/wopi/files/
      REACT_APP_INS_EDITOR_URL: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?WOPISrc=https://local.antecedentwriting.com/wopi/files/
      REACT_APP_PEERREVIEW: https://local.antecedentwriting.com/browser/b6712dc6c4/cool.html?WOPISrc=https://local.antecedentwriting.com/review/wopi/files/
    image: quay.io/antecedent.writing.analytics/awaui:LT-latest
    ports:
    - 3000:3000
    restart: always
  AWAWP:
    container_name: awawp
    
    env_file:
    - ./vars/.awawp.env
    ports:
    - 8000:8000
    environment:
      MONGO_SECRET: S3cretP6ss
    image: quay.io/antecedent.writing.analytics/awawp:LT-latest
    restart: always
  COLLABORA:
    container_name: collabora
    env_file:
    - ./vars/.collabora.env
    environment:
      domain: https://local.antecedentwriting.com
      server_name: local.antecedentwriting.com
    image: collabora/code
    ports:
    - 9980:9980
    restart: always
    volumes:
    - ./python:/opt/collaboraoffice/share/Scripts/python
  CONVERTER:
    container_name: converter
    env_file:
    - ./vars/.converter.env

    image: quay.io/antecedent.writing.analytics/converter:LT-latest
    restart: always
  certbot:
    command: certonly --webroot --webroot-path=/var/www/certbot --email yashar.ghaemi@antecedent.us
      --agree-tos --no-eff-email -d local.antecedentwriting.com
    container_name: certbot
    image: certbot/certbot
    volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
  
  spellcheck:
    container_name: spellcheck
    image: collabora/languagetool
    restart: unless-stopped
  webserver:
    container_name: webserver
    image: nginx:1.15.12-alpine
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./nginx-conf/:/etc/nginx/conf.d
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
volumes:
  certbot-etc:
    driver: local
  certbot-www:
    driver: local
