services:
  ANTECEDENT:
    container_name: antecedent
    depends_on:
    - mongodb
    env_file:
    - ./vars/.antecedent.env
    environment:
      Antecedent.app.Email.From: a@a.a
      Antecedent.app.jwtSecret: NvRvnn2LCqcbsqsG1b49OnNGEO6Ya9vDipd5WFIOTvv69M5jMy7MpF9KQqi0LFfzBeNxaBQDwdLoNS1EoQXRGE9AvKHMVpUs
      Antecedent.app.ui: https://app.py/
      Antecedent.app.url: https://app.py/
      spring.data.mongodb.password: qfEM1qTGXc8e
      spring.mail.host: smtp.gmail.com
      spring.mail.password: password
      spring.mail.port: 587
      spring.mail.username: a@a.a
    image: antecedent
    ports:
    - 8080:8080
    restart: always
  AWAUI:
    container_name: awaui
    env_file:
    - ./vars/.awaui.env
    environment:
      REACT_APP_ADMIN_EDITOR_URL: https://app.py/browser/77a0aab/cool.html?WOPISrc=http://app.py/admin/wopi/files/
      REACT_APP_API_URL: http://app.py
      REACT_APP_COLLABORA_HOST: https://app.py/browser/77a0aab/cool.html?
      REACT_APP_EDITOR_URL: https://app.py/browser/77a0aab/cool.html?WOPISrc=http://app.py/wopi/files/
      REACT_APP_EDU_EDITOR_URL: https://app.py/browser/77a0aab/cool.html?WOPISrc=http://app.py/shadow/wopi/files/
      REACT_APP_INS_EDITOR_URL: https://app.py/browser/77a0aab/cool.html?WOPISrc=http://app.py/wopi/files/
      REACT_APP_PEERREVIEW: https://app.py/browser/77a0aab/cool.html?WOPISrc=http://app.py/review/wopi/files/
    image: awaui
    ports:
    - 3000:3000
    restart: always
  AWAWP:
    container_name: awawp
    depends_on:
    - mongodb
    env_file:
    - ./vars/.awawp.env
    environment:
      MONGO_SECRET: qfEM1qTGXc8e
    image: awawp
    restart: always
  COLLABORA:
    container_name: collabora
    env_file:
    - ./vars/.collabora.env
    environment:
      domain: https://app.py
      server_name: app.py
    image: collabora/code
    ports:
    - 9980:9980
    restart: always
    volumes:
    - ./python:/opt/collaboraoffice/share/Scripts/python
  certbot:
    command: certonly --webroot --webroot-path=/var/www/certbot --email emai@app.py
      --agree-tos --no-eff-email -d app.py
    container_name: certbot
    image: certbot/certbot
    volumes:
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
  mongodb:
    command: mongod --wiredTigerCacheSizeGB 2
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_PASSWORD: qfEM1qTGXc8e
      MONGO_INITDB_ROOT_USERNAME: root
    image: mongo
    restart: always
    volumes:
    - ./mongo-data:/data/db
    - ./backups:/backups
  spellcheck:
    container_name: spellcheck
    image: collabora/languagetool
    restart: unless-stopped
  webserver:
    container_name: webserver
    image: nginx:1.15.12-alpine
    ports:
    - 80:80
    restart: unless-stopped
    volumes:
    - ./nginx-conf/:/etc/nginx/conf.d
    - certbot-etc:/etc/letsencrypt
    - certbot-www:/var/www/certbot
version: '3'
volumes:
  certbot-etc:
    driver: local
  certbot-www:
    driver: local
